final Map<String, List<String>> predefinedSubCategories = {
  "Technology": [
    "Software Development",
    "Web Development",
    "Mobile App Development",
    "DevOps",
    "Cloud Computing",
    "IT Support",
    "Network Administration",
    "Database Administration",
    "Systems Engineering",
    "Game Development",
  ],
  "Business": [
    "Management",
    "Business Strategy",
    "Entrepreneurship",
    "Consulting",
    "Operations Management",
  ],
  "Design": [
    "Graphic Design",
    "UX/UI Design",
    "Product Design",
    "Interior Design",
    "Fashion Design",
  ],
  "Data Analysis": [
    "Data Science",
    "Data Engineering",
    "Business Intelligence",
    "Statistical Analysis",
    "Data Visualization",
  ],
  "Artificial Intelligence": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "AI Research",
  ],
  "Finance": [
    "Accounting",
    "Financial Analysis",
    "Auditing",
    "Investment Banking",
    "Tax Consulting",
  ],
  "Marketing": [
    "Digital Marketing",
    "Content Marketing",
    "SEO/SEM",
    "Social Media Marketing",
    "Brand Management",
  ],
  "Engineering": [
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Chemical Engineering",
    "Environmental Engineering",
  ],
  "Education": [
    "Teaching",
    "Tutoring",
    "Curriculum Development",
    "E-Learning",
    "Research",
  ],
  "Healthcare": [
    "Nursing",
    "Medical Assistance",
    "Pharmacy",
    "Public Health",
    "Medical Administration",
  ],
  "Legal": [
    "Corporate Law",
    "Criminal Law",
    "Intellectual Property",
    "Legal Consulting",
    "Compliance",
  ],
  "Retail": [
    "Store Management",
    "Sales",
    "Merchandising",
    "E-Commerce",
    "Customer Service",
  ],
  "Media & Entertainment": [
    "Film Production",
    "Broadcasting",
    "Journalism",
    "Animation",
    "Music Production",
  ],
  "Cybersecurity": [
    "Network Security",
    "Ethical Hacking",
    "Cyber Forensics",
    "Information Security",
    "Security Compliance",
  ],
  "Customer Support": [
    "Help Desk",
    "Technical Support",
    "Live Chat",
    "Client Relations",
    "Customer Service",
  ],
  "Human Resources": [
    "Recruitment",
    "Employee Engagement",
    "Payroll",
    "HR Strategy",
    "Training and Development",
  ],
  "Supply Chain": [
    "Logistics",
    "Procurement",
    "Inventory Management",
    "Distribution",
    "Operations",
  ],
  "Arts & Culture": [
    "Fine Arts",
    "Performing Arts",
    "Museum Studies",
    "Cultural Management",
    "Art Curation",
  ],
};
