name: project_bc_tuto
description:
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1



#-------------------------------Packages-------------------------$
dependencies:
  flutter:
    sdk: flutter

# utility packages
  http: ^1.1.8
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.2.12
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.4
  vertical_percent_indicator: ^0.0.1



  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  #state flutter_state_management:
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true



#----------------------------Assets-----------------------#

#-------------------------local assets--------------------#
  assets:
    - assets/logos/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/Users/
    - assets/images/content/user_type/


#--------------------------local fonts---------------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/popins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/popins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/popins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/popins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/popins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/popins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/popins/Poppins-Bold.ttf
          weight: 800

