// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQT_dwFaaIYpQeqqnOKk-iwDXSRSdc7RY',
    appId: '1:115093062858:web:aff397729d9622d6cbe033',
    messagingSenderId: '115093062858',
    projectId: 'jimp-9e096',
    authDomain: 'jimp-9e096.firebaseapp.com',
    storageBucket: 'jimp-9e096.firebasestorage.app',
    measurementId: 'G-JS1CVV7QS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVOqiaU5lezobXSlD6c3ptxfYiUknElI',
    appId: '1:115093062858:android:10282312d054ea97cbe033',
    messagingSenderId: '115093062858',
    projectId: 'jimp-9e096',
    storageBucket: 'jimp-9e096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbEo7yII1Ipl-DP3ZwiKaA5cTdSMSPyp4',
    appId: '1:115093062858:ios:5da003a0c755335acbe033',
    messagingSenderId: '115093062858',
    projectId: 'jimp-9e096',
    storageBucket: 'jimp-9e096.firebasestorage.app',
    androidClientId: '115093062858-ol3fr1khptbgc49n0q0l4l4oj7p852r1.apps.googleusercontent.com',
    iosClientId: '115093062858-t5spk21hv1maftdcen4t8bu25u46hir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBcTuto',
  );

}